name: CI

on:
  push:
    branches: [main, master]
  pull_request:
    branches: [main, master]

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  quick-checks:
    name: Quick Checks
    runs-on: ubuntu-latest
    timeout-minutes: 5
    
    steps:
      - uses: actions/checkout@v4
      
      - uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'
      
      - run: npm ci --no-audit --no-fund
      
      - name: Type check
        run: npm run typecheck
        if: ${{ hashFiles('tsconfig.json') != '' }}
      
      - name: Lint
        run: npm run lint
        if: ${{ hashFiles('.eslintrc*', 'eslint.config.js') != '' }}
      
      - name: Format check
        run: npm run format:check
        if: ${{ hashFiles('.prettierrc*', 'prettier.config.js') != '' }}

  test:
    name: Tests
    runs-on: ubuntu-latest
    timeout-minutes: 10
    
    steps:
      - uses: actions/checkout@v4
      
      - uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'
      
      - run: npm ci --no-audit --no-fund
      
      - name: Build
        run: npm run build
        if: ${{ hashFiles('package.json') != '' }}
      
      - name: Run tests
        run: npm test
        if: ${{ hashFiles('package.json') != '' }}

